[tool.isort]
profile = "black"
line_length = 100

[tool.black]
line-length = 100

[tool.pylint]
fail-under=9.5
[tool.pylint.'MASTER']
ignore=['venv', 'tests']
[tool.pylint.'FORMAT']
max-line-length=['100']
