name: Python library

on:
  push:
    branches:
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        make venv

    - name: Static tests
      run: |
        make static

    - name: Unit tests
      run: |
        make unit

    - name: Integration tests
      run: |
        make integration

  build:
    runs-on: ubuntu-22.04
    needs: tests

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        make venv

    - name: Build package
      run: |
        make

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: call-center-tools
        path: dist/
